# Generated by Django 6.0 on 2025-12-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_production',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True),
        ),
    ]
